export enum StatusAtribuicao {
  DISPONIVEL = 'DISPONIVEL',
  ATRIBUIDO = 'ATRIBUIDO',
  EM_CONVERSA = 'EM_CONVERSA',
  NEGOCIACAO = 'NEGOCIACAO',
  CONCLUIDO_SUCESSO = 'CONCLUIDO_SUCESSO',
  CONCLUIDO_RECUSADO = 'CONCLUIDO_RECUSADO',
}

export enum ProcessoSituacao {
  ATIVO = 'ATIVO',
  ARQUIVADO = 'ARQUIVADO',
  BAIXADO = 'BAIXADO',
}

export enum TipologiaProcesso {
  JUDICIAL = 'JUDICIAL',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
}

export enum ProcessoSituacao {
  AGUARDANDO_DISTRIBUICAO = 'AGUARDANDO_DISTRIBUICAO',
  PENDENTE_ENRIQUECIMENTO = 'PENDENTE_ENRIQUECIMENTO',
  EM_ENRIQUECIMENTO = 'EM_ENRIQUECIMENTO',
  ENRIQUECIDO = 'ENRIQUECIDO',
  DESCARTADO_SCORE_BAIXO = 'DESCARTADO_SCORE_BAIXO',
  PROPOSTA_APRESENTADA = 'PROPOSTA_APRESENTADA',
  FINALIZADO = 'FINALIZADO',
  ERRO_PROCESSAMENTO = 'ERRO_PROCESSAMENTO'
}
