export enum StatusAtribuicao {
  NAO_DISPONIVEL = 'NAO_DISPONIVEL',
  DISPONIVEL = 'DISPONIVEL',
  ATRIBUIDO = 'ATRIBUIDO',
  EM_CONVERSA = 'EM_CONVERSA',
  EM_NEGOCIACAO = 'EM_NEGOCIACAO',
  CONCLUIDO_SUCESSO = 'CONCLUIDO_SUCESSO',
  CONCLUIDO_RECUSADO = 'CONCLUIDO_RECUSADO',
}

export enum ResultadoAtendimento {
  ACEITOU = 'ACEITOU',
  RECUSOU = 'RECUSOU',
}

export enum TipologiaProcesso {
  JUDICIAL = 'JUDICIAL',
  ADMINISTRATIVO = 'ADMINISTRATIVO',
}

export enum ProcessoSituacao {
  AGUARDANDO_DISTRIBUICAO = 'AGUARDANDO_DISTRIBUICAO',
  PENDENTE_ENRIQUECIMENTO = 'PENDENTE_ENRIQUECIMENTO',
  EM_ENRIQUECIMENTO = 'EM_ENRIQUECIMENTO',
  ENRIQUECIDO = 'ENRIQUECIDO',
  DESCARTADO_SCORE_BAIXO = 'DESCARTADO_SCORE_BAIXO',
  PROPOSTA_APRESENTADA = 'PROPOSTA_APRESENTADA',
  FINALIZADO = 'FINALIZADO',
  ERRO_PROCESSAMENTO = 'ERRO_PROCESSAMENTO'
}
