export * from './enums.model';
export * from './pagination.model';
export * from './processo-resumo.model';
export * from './score-item.model';
export * from './evento-contato.model';
export * from './processo-detalhe.model';
export * from './atribuicao-processo-resumo.model';
export * from './processo-contato.model';
export * from './etiqueta.model';
